/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const showNotify: typeof import('vant/es')['showNotify']
  const showToast: typeof import('vant/es')['showToast']
}
